### ISSUE TITLE
shouldContainAll

### ISSUE THREAD

**Issue by AndreasVolkmann** [MarkusAmshove/Kluent#100]
I think we are missing the `shouldContainAll` type of extensions. 

This one covers my current use case:
`infix fun String.shouldContainAll(items: Iterable<CharSequence>): List<CharSequence> = items.map(::shouldContain)`

Instead of:
```
ids.forEach {
    sql shouldContain it.toString()
}
```
This should be possible:
`sql shouldContainAll ids.map(Int::toString)`

But this should also apply to Iterables. 
`listOf(1) shouldNotContainAll listOf(4)`

**Comment by AndreasVolkmann** [comment]
@MarkusAmshove I just realized how annoying it is to write tests for both the backtick and non-backtick version. 
It's basically copy paste, but both versions have to be maintained even though they use the same logic. 

Wouldn't it be better if we had a Spek wrapper that took an Iterable of functions and then ran the specified tests for each of them? 

Just an idea, which could reduce the test code size by half. 
It's also really annoying to have so many files in the IDE.

**Comment by MarkusAmshove** [comment]
@AndreasVolkmann I feel you 😃 

The intent was to use the tests as a kind of documentation of usage at first, but the number of assertions really exploded after the initial release.

It's okay for me if you don't write the backtick tests, because Spek will be removed in the future (atleast for most of the assertions which are platform independent) and I'll migrate the tests to `kotlin.test`.

**Comment by MarkusAmshove** [comment]
I've published 1.37, which contains this change ✔️
