### ISSUE TITLE
Add withCause

### ISSUE THREAD

**Issue by okkero** [MarkusAmshove/Kluent#24]
It would be nice to be able to assert that an expected exception has a specific cause, like you can assert that it has a specific message. Something like the following:

```kotlin
func `should throw the Exception` MyException::class `with cause` IndexOutOfBoundsException::class
```

**Comment by goreRatzete** [comment]
Great work @okkero !
Hmm, now there is shouldThrow and shouldThrowTheException.

Maybe I am missing something, but do we need both?

Could the shouldThrow return the ExceptionResult ?

**Comment by okkero** [comment]
It does seem a bit unnecessary

**Comment by goreRatzete** [comment]
Ok I took a look at the code. 

It is possible to make shouldThrow also return an ExceptionResult, but for the shouldNotThrow part, I don't see any possibility.

**Comment by MarkusAmshove** [comment]
The reasoning was that the shouldNotThrow function can't decide whether it should fail fast (because the thrown Exception shouldn't be thrown) or shouldn't fail itself because there's a chained assertion on the message (or now also an inner exception). 
I'm open for new names though :-)

The reasoning behind the naming was that shouldThrow has a semantic of "anything Exception that subtypes the expected type" and shouldThrowTheException being more specific about the Exception itself (e.g. the message)

**Comment by goreRatzete** [comment]
Yes, I discovered the same thing when playing with the code. 

It is possible however to at least merge the `shouldThrow ` and `shouldThrowTheException` methods into one.

I have made a fork where I merged them. 
You can see it here: [My commit](https://github.com/goreRatzete/Kluent/commit/229df00e69145a1c3955d76250184d206c0ba39f)
