### ISSUE TITLE
Maven pom refers to "plus sign" versions of dependencies

### ISSUE THREAD

**Issue by binkley** [MarkusAmshove/Kluent#37]
I'm using maven 3.3.9, and am unable to resolve these dependencies from the Kluent 1.1.7 pom:
* org.jetbrains.kotlin:kotlin-stdlib:jar:1.1.+
* org.jetbrains.kotlin:kotlin-reflect:jar:1.1.+
* com.nhaarman:mockito-kotlin:jar:1.3.+

That I'm aware of, the "plus sign" is not valid for resolving.  The documentation on this is a bit scattered, but I believe this works: http://maven.apache.org/enforcer/enforcer-rules/versionRanges.html.

Perhaps `[1.1,1.2)` would work (meaning at least 1.1, but not yet 1.2)?

**Comment by MarkusAmshove** [comment]
I'm not using maven so I wasn't aware that this would be a problem.

It seems like the gradle generated POM contains the + signs (as you suggested) and maven doesn't like that.

The version ranges seem the way to go, I'll have a look if gradle can generate them correctly or, which I would prefer, fix the versions used to create the jar in the pom. Because otherwise we might see a breaking library if any dependency makes a breaking change (within a minor version).

Thanks for pointing me to this!

**Comment by MarkusAmshove** [comment]
It seems to be an open issue at gradle (dated in 2015)

https://issues.gradle.org/browse/GRADLE-3224

which is ported to

https://github.com/gradle/gradle/issues/1232


I think the only way to solve this by now is using fixed versions for releases. 
I'll try it today and release a fixed version (1.18) if it works that way

**Comment by MarkusAmshove** [comment]
I've released v1.18 with a workaround which I found on stackoverflow (http://stackoverflow.com/a/32353697/6556970).

I've tested it locally with maven and it works, can you confirm that for me? :-)

The dependency would now be

```xml
<dependency>
    <groupId>org.amshove.kluent</groupId>
    <artifactId>kluent</artifactId>
    <version>1.18</version>
    <type>pom</type>
</dependency>
```

**Comment by binkley** [comment]
Oh very much nicer, thank you!

**Comment by MarkusAmshove** [comment]
Thank you for pointing this issue out :-)

**Comment by binkley** [comment]
FYI, I spotted a Kotlin project (several, actually, under Kohesive) showing in it's `README.md`  the use of `+` for Gradle, and version range for Maven, if you're interested -- https://github.com/kohesive/kovert

```groovy
compile "uy.kohesive.kovert:kovert-vertx:1.1.+"
```
```xml
<dependency>
    <groupId>uy.kohesive.kovert</groupId>
    <artifactId>kovert-vertx</artifactId>
    <version>[1.1.0,1.2.0)</version>
</dependency>
```

**Comment by MarkusAmshove** [comment]
You can also use the + (in gradle) or range (in maven) to include Kluent.

The problem was that Kluent was using + versions in its own build (for example depending on kotlin-stdlib) and the Kluent-POM which was generated for Maven then had dependencies on kotlin-stdlib:1.1.+, which Maven doesn't understand.

Kovert seems to use dependencies with fixed version, so they won't have this problem :-)
Cool that you investigated it further! :+1:
