### ISSUE TITLE
Assert equals is not working for ByteArray

### ISSUE THREAD

**Issue by Tapchicoma** [MarkusAmshove/Kluent#42]
I was trying to compare if two `ByteArray` content is equal and saw following message:

```
java.lang.AssertionError: 
Expected :[B@4926097b
Actual   :[B@762efe5d
```
But when I use `Arrays.equal()` or `assertArrayEqual()` test is green.

To reproduce it add following code in test case:
```
val testArray = byteArrayOf(1, 3, 4, 12)
testArray.copyOf() `should equal` testArray
```

My suspicion is that for other similar arrays it will also not work.

**Comment by MarkusAmshove** [comment]
I've investigated and found that `byteArrayOf()` creates a `ByteArray` instead of `Array<Byte>`. Therefor it calls `Any.shouldEqual(Any)`.

If I change the testcode to:

```kt
val testArray = byteArrayOf(1, 3, 4, 12).toTypedArray()
testArray.copyOf() `should equal` testArray
```

it works as expected.

I wasn't aware that such types exist (I always use arrayOf and let the inference get the type).

I'll write functions for `IntArray`, `ByteArray` etc to have it sorted out :-)

**Comment by MarkusAmshove** [comment]
You can try version 1.21, the primitive arrays should be on par with the boxed ones now

**Comment by Tapchicoma** [comment]
Thanks. Working well.
