### ISSUE TITLE
File assertions!

### ISSUE THREAD

**Issue by goreRatzete** [MarkusAmshove/Kluent#47]
I know you have been working on something with File, but when are we getting File.shouldExist() ? 📁 

I can supply it.

**Comment by MarkusAmshove** [comment]
I'd be glad if you could supply it, I'm busy studying until July :-)

For the assertion site I've only implemented [two assertions](https://github.com/MarkusAmshove/Kluent/blob/fluent-filesystem/src/main/kotlin/org/amshove/kluent/FileSystem.kt), because I've originally wanted to implement the `TestFolder` system from JUnit, which didn't really work well for Kotlin/Spek yet.

**Comment by goreRatzete** [comment]
Here is my commit: #48  .

**Comment by goreRatzete** [comment]
Hmm I see you also have a File.shouldHaveName method. Might add it.

Other possibilities:
* isHidden

**Comment by MarkusAmshove** [comment]
If you want you can add them, but we can also add them when needed.

I like how the features are progressed as needed :-)

Just let me know when you're done so I can merge and update the documentation ;)

**Comment by goreRatzete** [comment]
I am done for now. 

Ended up adding the following:
* shouldHaveName
* shouldHaveExtension

Please merge =)

**Comment by MarkusAmshove** [comment]
Done, thank you :-)

it's included in 1.24
