### ISSUE TITLE
Should be equal inconsistency

### ISSUE THREAD

**Issue by AndreasVolkmann** [MarkusAmshove/Kluent#96]
I was looking for the `shouldBeEqual` infix for `Int`.

The String version has the following:
`infix fun String.shouldBeEqualTo(expected: String) = this.apply { assertEquals(expected, this) }`

But for Int there is only this:
`infix fun Int.`should be equal to`(expected: Int) = this.shouldEqualTo(expected)`

-> There is no `shouldBeEqual` without backticks for Int / numerical. 

Personally I also prefer `shouldEqualTo` over `shouldBeEqualTo`.

**Comment by MarkusAmshove** [comment]
You're right, this seems to be missing. I'll add it.

As for the renaming, I think we shouldn't break the naming now, as this would introduce more confusion :-)

**Comment by MarkusAmshove** [comment]
Ah now I see what you meant about the naming, the String method is breaking the "convention", as there is `Int.shouldEqualTo(Int)`

**Comment by AndreasVolkmann** [comment]
Hmm I am not quite sure. 

IIRC you introduced `shouldBeEqualTo` to be consistent with `shouldBe`. 

There is already a deprecation going on in the current version. 

It's a bit confusing 8)

**Comment by MarkusAmshove** [comment]
I now had the time to look more into it and you're right.
CharSequence/String has 

```kt
@Deprecated
shouldEqualTo

shouldBeEqualTo
```

Numericals only have
```kt
shouldEqualTo
```

There are several options we can do:
- Deprecate `shouldEqualTo` in Numericals and introduce `shouldBeEqualTo` (the same goes with `shouldNotBeEqualTo`
- Get CharSequence/String the other way around (deprecate `shouldBeEqualTo` to `shouldEqualTo`)

The first option has more impact because there will likely be more places it has to be changed (although IntelliJ can change it automatically), but `shouldBeEqualTo` seems to be more correct than `shouldEqualTo` (but maybe my English isn't profound enough to accept the latter :D ).
Also other assertions use the `be`, e.g. `shouldBeGreaterThan`, `shouldBeNegative`

The second option would be the one with the least impact in terms of code change, but might confuse users that just changed to `shouldBeEqualTo`.

I would love to have it consistent when we go to 2.0, but I'm not sure which way to go.
Opinions are welcomed :-)
